# Generated by Django 3.1.6 on 2021-02-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_npo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(null=True, upload_to='news_npo/'),
        ),
        migrations.AddField(
            model_name='news',
            name='link',
            field=models.TextField(null=True),
        ),
    ]
