# Generated by Django 3.1.6 on 2021-02-07 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_npo', '0002_auto_20210207_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.RemoveField(
            model_name='news',
            name='link',
        ),
    ]
