# Generated by Django 3.1.6 on 2021-02-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_npo', '0002_auto_20210208_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, null=True, verbose_name='email'),
        ),
    ]
