# Generated by Django 3.1.6 on 2021-02-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_npo', '0003_auto_20210207_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
