# Generated by Django 3.1.6 on 2021-02-11 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_npo', '0005_auto_20210211_1644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
